Make sure a patch file was created before losing changes
A comment on my blog said he lost work when the patch file failed to
be created. Good feedback and I'm glad he didn't lose too much
data. Check that the file exists before reverting local changes

diff --git a/home/.git-templates/hooks/pre-commit b/home/.git-templates/hooks/pre-commit
--- a/home/.git-templates/hooks/pre-commit
+++ b/home/.git-templates/hooks/pre-commit
@@ -13,8 +13,14 @@ git diff --exit-code --binary --ignore-submodules --no-color > $patch_filename
 has_unstaged_changes=$?
 
 if [ $has_unstaged_changes -ne 0 ]; then
-    echo "Stashing unstaged changes in $patch_filename."
-    git checkout -- .
+    # Unstaged changes have been found
+    if [ ! -f "$patch_filename" ]; then
+        echo "Failed to create a patch file"
+        exit 1
+    else
+        echo "Stashing unstaged changes in $patch_filename."
+        git checkout -- .
+    fi
 fi
 
 quit() {
